services:
  web:
    build: .
    env_file: 
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - EDITOR_ENABLED=false
      - NODE_ENV=production
    volumes:
      - ./.env:/app/.env:ro
      - uploads:/app/server/public/uploads
      - ./data:/app/data
      - ./microservices/integracion_mercadopago_app:/app/microservices/integracion_mercadopago_app

    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: unless-stopped

volumes:
  uploads:
  caddy_data:
  caddy_config:
