services:
  web:
    build: .
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - uploads:/app/server/public/uploads
      - ./data:/app/data
      - ./microservices/integracion_mercadopago_app:/app/microservices/integracion_mercadopago_app

    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      web:
        condition: service_healthy
    restart: unless-stopped

volumes:
  uploads:
  caddy_data:
  caddy_config:
